#!/usr/bin/env bash
# Regenerate walkthrough/README.md. All code blocks are extracted VERBATIM from
# the repository via sed; the exact command is printed beneath each snippet, so
# the walkthrough can never silently drift from the real sources.
# Screenshots: walkthrough/screenshots.sh (chrome headless, local files only).
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=walkthrough/README.md
: > "$OUT"

md() { cat >> "$OUT"; }

# snip <file> <sed-range> <lang> — verbatim extract with provenance footer.
# 4-backtick fences so snippets may themselves contain ``` (e.g. .qmd chunks).
snip() {
  {
    echo
    echo "\`\`\`\`$3"
    sed -n "$2" "$1"
    echo "\`\`\`\`"
    echo "<sub>verbatim from [\`$1\`](../$1) — \`sed -n '$2' $1\`</sub>"
    echo
  } >> "$OUT"
}

md <<'EOF'
# KONjecture-alpha — a linear walkthrough

*Generated by [`build.sh`](build.sh) — do not edit by hand. Every code block below is
extracted verbatim from the repository by `sed` (the exact command is printed under each
snippet). Screenshots are captured from the committed static pages by
[`screenshots.sh`](screenshots.sh).*

This document retells the project so far in the order it actually happened:
vision → market research → one deliberate decision → schema → data → pages →
models → a language port → tests → dashboard.

---

## 1 · What this is

An open-source platform (vision stage, [Issue #1](https://github.com/hzmchen/KONjecture-alpha/issues/1))
for serving, comparing, and evaluating real-time GDP nowcasts across regions. Two premises
set the decision lens for everything below ([research/00](../research/00-methodology-and-rubrics.md)):

- **P-A — Liebhaberei.** A one-person side project; success = sustained enjoyment and
  learning. The project must tolerate dormancy: artifacts announce their own staleness,
  and nothing requires standing infrastructure.
- **P-B — AI-assisted build.** Writing code is cheap; *maintainer attention* (validation,
  operations, obligations) is the scarce resource. Build-vs-reuse tilts toward thin
  bespoke glue over heavy dependencies; *standards* (hubverse formats) are still adopted.

## 2 · Market research (2026-06-10)

Nine research docs ([research/](../research/)) covered supply, demand, synthesis, delivery
risks, vintage reconstruction, a survivorship-bias sweep of dead comparable projects, and a
pre-mortem. A component catalog ([research/components/](../research/components/README.md))
then verified every intended building block. Its headline findings:
EOF
snip research/components/README.md '/^1\. \*\*The full intended stack/,/^5\./p' text
md <<'EOF'
The prioritized outcome was five "Now" items in [TODO.md](../TODO.md): **N1** decide the
evaluation target measure, **N2** a riskiest-assumption pipeline spike, **N3** a
Wizard-of-Oz comparison page, **N4** seed the archive retroactively, **N5** a webR/WASM
audit (already done during research: 31/32 stack packages have WASM binaries).

## 3 · The one real decision: what does "right" mean? (N1, Issue #2)

GDP is revised for years, so "the nowcast was right" is ill-posed until you name the
target. Critical review ([research/09](../research/09-target-measure-decision.md)) found
the schema question was already self-resolved — store *every* outcome vintage and any
target rule is computable later — which narrowed N1 to defaults. The owner confirmed
option 4 of the issue:
EOF
snip research/09-target-measure-decision.md '/^| Role |/,/dormancy-tolerant/p' text
md <<'EOF'
Residual sub-decisions (D1 per-region "first release", D2 the fixed-horizon k, D3 units,
D4 dual-ranking presentation) were parked exactly where they gate work.

## 4 · Schema: scores are (forecast, target-rule) pairs

[docs/schema.md](../docs/schema.md) encodes the decision: outcome rows carry their own
publication vintage; canonical units are non-annualized q/q growth with SAAR as a display
transform; and target rules are named, never implied:
EOF
snip docs/schema.md '/^## Target rules/,/^Append-only/p' markdown
md <<'EOF'
## 5 · Seeding the archive (N4)

Two strictly separated stages ([ingest/](../ingest/README.md)). The **network stage** is a
deliberate manual act — one polite GET per source into an append-only cache with SHA-256
provenance, never a build side effect. One entry of the source register:
EOF
snip ingest/download_raw.R '/^  gdpnow = list(/,/^  ),$/p' r
md <<'EOF'
The **transform stage** normalizes the cache into `data/archive/` (3,285 forecasts from
GDPNow 2011→ daily incl. the live quarter, NY Fed 2022→ weekly, Philly SPF 1968→, ECB SPF
1999→; 59 vintage-dated BEA advance outcomes). The canonical unit conversion is one line:
EOF
snip ingest/build_archive.R '/^saar_to_qq/p' r
md <<'EOF'
Validation attention earned its keep immediately: the first ECB parser leaked unemployment
rows (~6.5%) into GDP means because the next section header says "EXPECTED", not
"EXPECTATIONS" — a spot check (individuals ~0.8–1.3 ⇒ mean must be ≈1, not 3.4) caught it.
The fixed boundary detection:
EOF
snip ingest/build_archive.R '/# section headers = prose rows/,/end <- if/p' r
md <<'EOF'
## 6 · The Wizard-of-Oz comparison page (N3)

Before building any model: is the *comparison itself* useful? A static, self-contained
page (no server, no external assets) generated from the archive answers that with real
data — including GDPNow's 3.70 → 1.19 slide over the 2026Q2 cycle:

![The N3 comparison page: value tiles, evolution chart, 12-quarter track record, tables](img/n3-comparison-page.png)

Two design requirements came straight from the pre-mortem and the target-measure decision.
Self-announcing staleness (08 F3) — the page carries a dormant-mode banner that activates
itself after 45 days:
EOF
snip site/template.html '/var built = new Date/,/display = .block./p' js
md <<'EOF'
And a target disclosure (09 D4): every score on the page names the first release as its
target. One R-specific bug from this stage is preserved as a regression test — `gsub`
interprets `&` in replacements even with `fixed=TRUE`, which would corrupt every `&amp;`:
EOF
snip site/R/site_lib.R '/# split\/join instead of gsub/,/^}/p' r
md <<'EOF'
## 7 · The riskiest-assumption spike (N2)

Can one person run data → benchmark + factor model → probabilistic output → append-only
archive, reproducibly, with zero standing infrastructure? The `targets` pipeline says yes:
one full run builds everything, a second run skips all targets. The two models, honest and
minimal — an AR(2) benchmark and a DFM bridge on `dfms` (the R3-"adopt" estimation core):
EOF
snip pipeline/R/functions.R '/^ar_benchmark <- function/,/^}/p' r
snip pipeline/R/functions.R '/^dfm_bridge <- function/,/^}/p' r
md <<'EOF'
Output is hubverse-style (point + 7 quantiles, `declared_target = "advance"`), appended
with keyed dedupe. For 2026Q2 the spike produced AR(2) 2.82 vs DFM bridge 3.25 %SAAR —
model *quality* is explicitly out of scope until scoring (X2) exists.

## 8 · The pure-R port

The first implementation was Python (only runtime available on day one) + R (models).
Assessment: one runtime is strategically better under P-A/P-B, and the port risk was
retired empirically — `readxl` even reads the Philly xlsx that crashed Python's openpyxl.
Method: freeze the Python outputs as golden files, port, and diff. Result: archive
row-for-row identical except **one cell** (an exact survey mean of 2.92225, where R's
half-even rounding gives the correct 2.9222); the generated page byte-identical. The
whole build now hangs off one dependency graph:
EOF
snip pipeline/_targets.R '1,$p' r
md <<'EOF'
## 9 · Tests and coverage

121 offline `testthat` tests (`Rscript tests/run_tests.R`); the committed raw cache is the
fixture set, writes go only to tempdirs, and download paths are exercised via `file://`
URLs and a refused localhost connection — never a real provider. Both ECB parser traps are
pinned forever:
EOF
snip tests/testthat/test-archive.R '/two known traps/,/^})/p' r
md <<'EOF'
Coverage (`Rscript tests/coverage.R`, `covr`):
EOF
snip tests/COVERAGE.md '/^| File |/,/\*\*Total\*\*/p' text
md <<'EOF'
## 10 · The Quarto dashboard (X5 fallback)

A static dashboard (`quarto render site/dashboard.qmd`, self-contained HTML) that adds
*layout only* — value boxes, tabs, staleness banner — around the same tested chart
library the N3 page uses, so both views agree by construction:

![The Quarto dashboard: value boxes and the Now-evolution tab](img/dashboard-now.png)

A value box is a few lines of qmd delegating to `site_lib.R`:
EOF
snip site/dashboard.qmd '/#| content: valuebox/,/^```$/{p; /^```$/q;}' markdown
md <<'EOF'
In the pipeline it is a soft dependency — `tar_make()` stays runnable from R alone:
EOF
snip pipeline/R/functions.R '/^render_dashboard <- function/,/^}/p' r
md <<'EOF'
## 11 · Where it stands

All five Now-items are done; the commit trail below is the project's actual linear
history. Open gates: **D1+D2** (per-region first-release definition, fixed-horizon k)
unlock scoring (X2); **ALFRED vintages** need a free API key; owner-side: merge the two
branches, close Issue #2.
EOF
{
  echo
  echo '````text'
  git log --reverse --format='%h %s' | sed -n '1,$p'
  echo '````'
  echo "<sub>generated at build time — \`git log --reverse --format='%h %s'\`</sub>"
} >> "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
